### ISSUE TITLE
S-Meter calibration

### ISSUE THREAD

**Issue by Starmike98** [f5bud/FX-4CR-V2#1]
My S-Meter is reading really low.  Is there a calibration with that.  I did the power calibration, voltmeter calibration, and watt meter calibration

**Comment by f5bud** [comment]
Hi Starmike,
I'm working on it.
In a day or two there will be a new release.
I will let you know.
Can you give me a general opinion on this version.
Thank you, 73 Daniel

Le mar. 27 févr. 2024 à 19:32, Starmike98 ***@***.***> a
écrit :

**Comment by KX5SP** [comment]
Daniel - your V2 firmware is terrific. I notice on most out-of-band (MARS) freqs the power seems to be limited to 2 watts. Is this  intentional? There is one band just below 20 meters (around 13.6MHz) where it will put out a full 20 watts. Thanks.
73,
Steve KX5SP

**Comment by f5bud** [comment]
Hi Steve,
Thank you for the compliments.
There is no function that reduces power outside the amateur bands. I think
it's due to the output filters.
You should draw the response curve to get an idea.
Be careful not to burn out the output transistors because apart from the
filters the VSWR must rise very quickly.

73, Daniel F5BUD
